# 上游触发器, 触发下游 project, 并传递 IMAGE_VER 变量
.triggerUpstreamBasic:
  stage: deploy
  inherit:
    variables: false
  variables: 
    IMAGE_VER: ${CI_COMMIT_SHORT_SHA}
  trigger: 
    project: root/test
    branch: $CI_COMMIT_BRANCH
    strategy: depend

# 根据 branch 来调用触发器
.triggerUpstreamBranch:
  extends: .triggerUpstreamBasic
  trigger: 
    branch: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH

# 根据 tag 来调用触发器
.triggerUpstreamTag:
  extends: .triggerUpstreamBasic
  trigger: 
    branch: master
  rules:
    - if: $CI_COMMIT_TAG
      variables: 
        IMAGE_VER: ${CI_COMMIT_TAG}